spring.application.name=avarESG
# Logging
app.logging.verbose=true

logging.file.name=logs/avar-esg.log
logging.level.root=INFO
logging.level.com.fatayriTech.avarESG=DEBUG

server.port=1990

spring.datasource.url=jdbc:postgresql://localhost:5432/avar_ESG
spring.datasource.username=mostafafatayri
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
api.prefix=/api/v1
app.notifications.email-enabled=true
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mostafafatayri@gmail.com
spring.mail.password=timj obzo tkxd pmyv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

